# Generated by Django 6.0 on 2025-12-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_content_remove_lesson_video_url_and_more'),
        ('enrollments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_course__180387_idx',
        ),
        migrations.RemoveIndex(
            model_name='lessonprogress',
            name='enrollments_user_id_59a2ae_idx',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='enrollmment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='enrollments.enrollment'),
        ),
        migrations.AddField(
            model_name='lessonprogress',
            name='watch_time',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollmment', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['user', 'course'], name='enrollments_user_id_ad8d71_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonprogress',
            index=models.Index(fields=['lesson', 'is_completed'], name='enrollments_lesson__f0214c_idx'),
        ),
    ]
