# Generated by Django 6.0 on 2025-12-16 07:03

from django.db import migrations

def link_lesson_progress(apps, schema_editor):
    Enrollment = apps.get_model('enrollments', 'Enrollment')
    LessonProgress = apps.get_model('enrollments', 'LessonProgress')

    for lp in LessonProgress.objects.all():
        enrollment = Enrollment.objects.filter(
            user=lp.user,
            course=lp.lesson.module.course
        ).first()
        if enrollment:
            lp.enrollment = enrollment
            lp.save(update_fields=['enrollment'])


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_remove_enrollment_enrollments_course__180387_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(link_lesson_progress, migrations.RunPython.noop),
    ]
