# Generated by Django 6.0 on 2025-12-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_content_remove_lesson_video_url_and_more'),
        ('enrollments', '0003_link_lesson_progress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonprogress',
            old_name='enrollmment',
            new_name='enrollment',
        ),
        migrations.AlterUniqueTogether(
            name='lessonprogress',
            unique_together={('enrollment', 'lesson')},
        ),
    ]
