# Generated by Codex on 2026-07-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_quiz_is_published_quiz_passing_percentage_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.UniqueConstraint(
                fields=("quiz", "user"),
                name="uniq_quiz_attempt_per_user",
            ),
        ),
    ]
