# Generated by Codex on 2026-07-23

from django.db import migrations


def delete_non_mcq_questions(apps, schema_editor):
    QuizQuestion = apps.get_model("assessments", "QuizQuestion")
    QuizQuestion.objects.exclude(question_type="mcq").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_quizattempt_single_attempt"),
    ]

    operations = [
        migrations.RunPython(delete_non_mcq_questions, migrations.RunPython.noop),
        migrations.DeleteModel(name="Rubric"),
        migrations.DeleteModel(name="Submission"),
        migrations.DeleteModel(name="Assignment"),
        migrations.RemoveField(
            model_name="quizquestion",
            name="question_type",
        ),
    ]
