# Generated by Codex on 2026-07-24

from django.db import migrations, models


def build_snapshot_for_quiz(QuizQuestion, quiz_id):
    snapshot = []
    questions = (
        QuizQuestion.objects
        .filter(quiz_id=quiz_id)
        .prefetch_related("options")
        .order_by("id")
    )

    for question in questions:
        snapshot.append({
            "question_id": question.id,
            "question_text": question.question_text,
            "difficulty": question.difficulty,
            "marks": question.marks,
            "options": [
                {
                    "option_id": option.id,
                    "option_text": option.option_text,
                    "is_correct": option.is_correct,
                }
                for option in question.options.all().order_by("id")
            ],
        })

    return snapshot


def backfill_attempt_snapshots(apps, schema_editor):
    QuizAttempt = apps.get_model("assessments", "QuizAttempt")
    QuizQuestion = apps.get_model("assessments", "QuizQuestion")

    for attempt in QuizAttempt.objects.all().iterator():
        snapshot = build_snapshot_for_quiz(QuizQuestion, attempt.quiz_id)
        attempt.question_snapshot = snapshot
        attempt.total_marks_snapshot = sum(
            int(question.get("marks") or 0)
            for question in snapshot
        )
        attempt.save(update_fields=["question_snapshot", "total_marks_snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_mcq_only"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizattempt",
            name="question_snapshot",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="total_marks_snapshot",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_attempt_snapshots, migrations.RunPython.noop),
    ]
