# Generated by Codex on 2026-07-23

from django.db import migrations, models


def backfill_role_staff_superuser_invariants(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_superuser=True).exclude(
        role="admin",
        is_staff=True,
    ).update(role="admin", is_staff=True)
    User.objects.filter(role="admin", is_staff=False).update(is_staff=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_wallet"),
    ]

    operations = [
        migrations.RunPython(
            backfill_role_staff_superuser_invariants,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(role="admin", is_staff=True)
                    | ~models.Q(role="admin")
                ),
                name="admin_role_requires_staff",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(is_superuser=False)
                    | models.Q(role="admin", is_staff=True)
                ),
                name="superuser_requires_admin_role_staff",
            ),
        ),
    ]
