# Generated by Codex on 2026-07-23

import hashlib

from django.db import migrations, models


def hash_existing_api_keys(apps, schema_editor):
    APIKey = apps.get_model("accounts", "APIKey")
    for api_key in APIKey.objects.all().iterator():
        secret = str(api_key.key)
        api_key.prefix = secret[:16]
        api_key.key_hash = hashlib.sha256(secret.encode("utf-8")).hexdigest()
        api_key.scopes = []
        api_key.save(update_fields=["prefix", "key_hash", "scopes"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_role_staff_superuser_invariants"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(blank=True, db_index=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="scopes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="apikey",
            name="last_used_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apikey",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(hash_existing_api_keys, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="apikey",
            name="key",
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="prefix",
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
