# Generated by Django 6.0 on 2026-07-24 04:32
# Backfills accounts.Profile.wallet balances into the canonical students.Wallet
# ledger, then drops the duplicate column.

from decimal import Decimal

from django.db import migrations


def backfill_wallets(apps, schema_editor):
    Profile = apps.get_model('accounts', 'Profile')
    Wallet = apps.get_model('students', 'Wallet')
    WalletTransaction = apps.get_model('students', 'WalletTransaction')

    for profile in Profile.objects.filter(wallet__gt=0).select_related('user'):
        wallet, _ = Wallet.objects.get_or_create(user=profile.user)
        profile_balance = profile.wallet or Decimal('0')
        # The Wallet is authoritative where it already holds funds; take the max
        # so no balance is ever lost, and skip when they already agree (avoids
        # double-counting balances that were kept in sync).
        target = max(wallet.balance, profile_balance)
        if target != wallet.balance:
            delta = target - wallet.balance
            wallet.balance = target
            wallet.save(update_fields=['balance', 'updated_at'])
            WalletTransaction.objects.create(
                wallet=wallet,
                transaction_type='credit',
                amount=delta,
                description='Backfill from accounts.Profile.wallet',
                balance_after=wallet.balance,
            )


def noop_reverse(apps, schema_editor):
    # Balances now live canonically in students.Wallet; nothing to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_passwordresettoken_user_and_more'),
        ('students', '0002_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RunPython(backfill_wallets, noop_reverse),
        migrations.RemoveField(
            model_name='profile',
            name='wallet',
        ),
    ]
