# Generated by Codex on 2026-07-23

from django.db import migrations, models


def backfill_attempt_numbers(apps, schema_editor):
    ExamAttempt = apps.get_model("exams", "ExamAttempt")

    pairs = (
        ExamAttempt.objects
        .values_list("exam_id", "user_id")
        .distinct()
    )
    for exam_id, user_id in pairs:
        attempts = (
            ExamAttempt.objects
            .filter(exam_id=exam_id, user_id=user_id)
            .order_by("started_at", "id")
        )
        for attempt_number, attempt in enumerate(attempts, start=1):
            if attempt.attempt_number != attempt_number:
                attempt.attempt_number = attempt_number
                attempt.save(update_fields=["attempt_number"])


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examattempt",
            name="attempt_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_attempt_numbers, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="examattempt",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                fields=("exam", "user", "attempt_number"),
                name="uniq_exam_attempt_number_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="examattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="in_progress"),
                fields=("exam", "user"),
                name="uniq_active_exam_attempt_per_user",
            ),
        ),
    ]
