# Generated by Codex on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_livesession_is_streaming_livesession_stream_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livesession',
            name='platform',
            field=models.CharField(
                choices=[
                    ('livekit', 'LiveKit'),
                    ('agora', 'Agora'),
                    ('zoom', 'Zoom'),
                    ('meet', 'Google Meet'),
                    ('teams', 'Microsoft Teams'),
                    ('custom', 'Custom Platform'),
                ],
                default='livekit',
                max_length=20,
            ),
        ),
    ]
