# Generated by Django 6.0 on 2025-12-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_lesson_content_remove_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
