# Generated by Django 6.0 on 2025-12-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_lesson_content_url_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
